# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(30, 370, 761, 211))
        self.log.setObjectName("log")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 350, 47, 14))
        self.label_2.setObjectName("label_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(71, 31, 681, 301))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setObjectName("groupBox")
        self.video = QtWidgets.QLabel(self.groupBox)
        self.video.setGeometry(QtCore.QRect(10, 20, 47, 14))
        self.video.setObjectName("video")
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 4)
        self.getCam = QtWidgets.QPushButton(self.widget)
        self.getCam.setObjectName("getCam")
        self.gridLayout.addWidget(self.getCam, 1, 0, 1, 1)
        self.shoot = QtWidgets.QPushButton(self.widget)
        self.shoot.setObjectName("shoot")
        self.gridLayout.addWidget(self.shoot, 1, 1, 1, 1)
        self.calibration = QtWidgets.QPushButton(self.widget)
        self.calibration.setObjectName("calibration")
        self.gridLayout.addWidget(self.calibration, 1, 2, 1, 1)
        self.closeCam = QtWidgets.QPushButton(self.widget)
        self.closeCam.setObjectName("closeCam")
        self.gridLayout.addWidget(self.closeCam, 1, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "日志打印："))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.video.setText(_translate("MainWindow", "video"))
        self.getCam.setText(_translate("MainWindow", "获取画面"))
        self.shoot.setText(_translate("MainWindow", "捕捉画面"))
        self.calibration.setText(_translate("MainWindow", "标定"))
        self.closeCam.setText(_translate("MainWindow", "关闭画面"))
